version: '3.8'
services:
  db:
    container_name: "db"
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
volumes:
  mongo_data: